### ISSUE TITLE
1.首页列表的数据获取

### ISSUE THREAD

**Issue by YMBo** [YMBo/react-ele#1]
在我编写完首页商家列表样式后，从饿了么获取商家数据，找不到接口，而且它的每次滚动加载，并没有发出请求，所以目前有两件事
1.临时获取饿了么首页商家列表的数据（主要是数据格式）
2.明白滚动加载在react怎么做

**Comment by YMBo** [comment]
已经解决，不过延伸出来另一个加载的情况，就是不利用原生滚动条那种下拉刷新，上滑加载，类似于好多app的那种模式，那个比这个复杂，多了几个事件和控制内容的移动

**Comment by windsome** [comment]
牛逼啊，我们合作吧。我有一个项目，类似大众点评。方便的的话，谈一谈。微信: agooou
