### ISSUE TITLE
运行 npm build 之后发布到 nginx，点击商店，提示 404

### ISSUE THREAD

**Issue by tryrefine** [YMBo/react-ele#13]
url是：/shop/wx4g09jvzy8w/436263
提示：404 not Found

开发环境：node 9.4.0, npm:5.6.0

请问这是怎么回事儿呢？

**Comment by YMBo** [comment]
nginx不熟悉，关于商家信息这一部分，每个商家的数据信息都是跨域请求的，在开发环境我通过webpack配置的代理服务，所以可以请求到，不知道你有没有配置相应的服务

**Comment by tryrefine** [comment]
我没有做任何配置，直接 build的。开发模式下（npm start），我通过 chrome 的手机模式看了，感觉挺不错。后来想放到线上用手机看效果。所以，就打包然后发布。

nginx 就是一个web 服务器，类似 express，build 的时候走的是 prod 的配置，开发环境可以配置的话，是不是意味着 prod 模式做同样的配置，打包之后也可以呢？

**Comment by YMBo** [comment]
开发环境能成功是因为本地启动了一个服务器里面有代理的设置，生产环境下你打包出来的只是静态文件，并没有任何的代理，所以你这样是会404的

**Comment by tryrefine** [comment]
好的，非常感谢

**Comment by tryrefine** [comment]
＠YMBo 加你ｑｑ好友了，能通过一下吗？希望跟您付费合作，我这边有一个小功能需要实现，对您来说应该相当简单

**Comment by 290352095** [comment]
@YMBo nginx该怎么配置一下呢？

**Comment by YMBo** [comment]
你需要用nginx做个代理，上面也提到了 ，这个是跨域请求的

**Comment by 290352095** [comment]
@YMBo 可现在报错是404，并不是跨域报错呀

**Comment by YMBo** [comment]
前台向服务器请求一个服务器没有配置的路由，当然是404了
